apiVersion: etcd.yj.io/v1alpha1
kind: EtcdCluster
metadata:
  labels:
    app.kubernetes.io/name: etcdcluster
    app.kubernetes.io/instance: etcdcluster-sample
    app.kubernetes.io/part-of: etcd-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: etcd-operator
  name: etcd
spec:
  size: 3  # 副本数量
  image: docker.io/cnych/etcd:v3.4.13  # 镜像
